#!/usr/bin/env bash
set -euo pipefail

NEOLINK_CONFIG="${NEOLINK_CONFIG:-/config/neolink/neolink.toml}"

mkdir -p /config/neolink

# Generate neolink.toml from environment variables
# Expected env vars per camera:
#   NEOLINK_ENABLED_<NAME>=true
#   NEOLINK_ADDRESS_<NAME>=<ip>
#   NEOLINK_USERNAME_<NAME>=<user>
#   NEOLINK_PASSWORD_<NAME>=<pass>

{
  echo "# Auto-generated by entrypoint.sh - do not edit manually"
  echo ""

  found=false
  for enabled_var in $(printenv | grep '^NEOLINK_ENABLED_' | cut -d= -f1); do
    camera_name="${enabled_var#NEOLINK_ENABLED_}"
    camera_name_lower="$(echo "${camera_name}" | tr '[:upper:]' '[:lower:]')"

    enabled_value=$(printenv "${enabled_var}")
    if [ "${enabled_value}" != "true" ]; then
      continue
    fi

    address_var="NEOLINK_ADDRESS_${camera_name}"
    username_var="NEOLINK_USERNAME_${camera_name}"
    password_var="NEOLINK_PASSWORD_${camera_name}"

    address=$(printenv "${address_var}" 2>/dev/null || echo "")
    username=$(printenv "${username_var}" 2>/dev/null || echo "")
    password=$(printenv "${password_var}" 2>/dev/null || echo "")

    if [ -z "${address}" ]; then
      echo "WARNING: ${address_var} not set, skipping camera ${camera_name_lower}" >&2
      continue
    fi

    found=true
    echo "[[cameras]]"
    echo "name = \"${camera_name_lower}\""
    echo "address = \"${address}\""
    if [ -n "${username}" ]; then
      echo "username = \"${username}\""
    fi
    if [ -n "${password}" ]; then
      echo "password = \"${password}\""
    fi
    echo ""
  done

  if [ "${found}" = false ]; then
    echo "# No neolink cameras enabled"
  fi
} > "${NEOLINK_CONFIG}"

echo "Neolink config generated at ${NEOLINK_CONFIG}"

# Hand off to Frigate's s6-overlay init
exec /init
